// Shared scalars + enums for the cmdop-core stdio contract.
//
// RFC3339 datetimes are carried as `string` (the relay stamps `...Z`,
// report 01 §2). UUIDs are carried as `string`. Nullable fields become
// `optional`.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file cmdop/core/v1/common.proto (package cmdop.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cmdop/core/v1/common.proto.
 */
export const file_cmdop_core_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChpjbWRvcC9jb3JlL3YxL2NvbW1vbi5wcm90bxINY21kb3AuY29yZS52MSIHCgVFbXB0eSIuCgpPZmZzZXRQYWdlEg4KBm9mZnNldBgBIAEoBRIQCghwZXJfcGFnZRgCIAEoBSqHAQoOTWZhUmVxdWlyZW1lbnQSHwobTUZBX1JFUVVJUkVNRU5UX1VOU1BFQ0lGSUVEEAASGAoUTUZBX1JFUVVJUkVNRU5UX05PTkUQARIcChhNRkFfUkVRVUlSRU1FTlRfT1BUSU9OQUwQAhIcChhNRkFfUkVRVUlSRU1FTlRfUkVRVUlSRUQQAyqTAQoSU2NoZWR1bGVUYXJnZXRLaW5kEiQKIFNDSEVEVUxFX1RBUkdFVF9LSU5EX1VOU1BFQ0lGSUVEEAASKwonU0NIRURVTEVfVEFSR0VUX0tJTkRfQUxMX0ZMRUVUX01BQ0hJTkVTEAESKgomU0NIRURVTEVfVEFSR0VUX0tJTkRfU1BFQ0lGSUNfTUFDSElORVMQAiq7AQoRU2NoZWR1bGVSdW5TdGF0dXMSIwofU0NIRURVTEVfUlVOX1NUQVRVU19VTlNQRUNJRklFRBAAEh8KG1NDSEVEVUxFX1JVTl9TVEFUVVNfUEVORElORxABEh8KG1NDSEVEVUxFX1JVTl9TVEFUVVNfUlVOTklORxACEh8KG1NDSEVEVUxFX1JVTl9TVEFUVVNfU1VDQ0VTUxADEh4KGlNDSEVEVUxFX1JVTl9TVEFUVVNfRkFJTEVEEARCtAEKEWNvbS5jbWRvcC5jb3JlLnYxQgtDb21tb25Qcm90b1ABWjxnaXRodWIuY29tL2NtZG9wL2NtZG9wL2dvL3BrZy9jb3JlcHJvdG8vY21kb3AvY29yZS92MTtjb3JldjGiAgNDQ1iqAg1DbWRvcC5Db3JlLlYxygINQ21kb3BcQ29yZVxWMeICGUNtZG9wXENvcmVcVjFcR1BCTWV0YWRhdGHqAg9DbWRvcDo6Q29yZTo6VjFiBnByb3RvMw");

/**
 * Empty is the body for every REST op that returns 204 No Content
 * (report 01: machines.disable, fleets.disable, fleet-machines.detach,
 * members.remove, tunnels.close, schedules.delete, keys.revoke).
 *
 * @generated from message cmdop.core.v1.Empty
 */
export type Empty = Message<"cmdop.core.v1.Empty"> & {
};

/**
 * Describes the message cmdop.core.v1.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_common, 0);

/**
 * OffsetPage carries the offset-pagination query fields used by
 * fleets / members / tunnels / keys / schedules-list (report 01 §11).
 *
 * @generated from message cmdop.core.v1.OffsetPage
 */
export type OffsetPage = Message<"cmdop.core.v1.OffsetPage"> & {
  /**
   * @generated from field: int32 offset = 1;
   */
  offset: number;

  /**
   * @generated from field: int32 per_page = 2;
   */
  perPage: number;
};

/**
 * Describes the message cmdop.core.v1.OffsetPage.
 * Use `create(OffsetPageSchema)` to create a new message.
 */
export const OffsetPageSchema: GenMessage<OffsetPage> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_common, 1);

/**
 * MfaRequirement mirrors FleetSummary.mfa_required (report 01 §4).
 *
 * @generated from enum cmdop.core.v1.MfaRequirement
 */
export enum MfaRequirement {
  /**
   * @generated from enum value: MFA_REQUIREMENT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MFA_REQUIREMENT_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: MFA_REQUIREMENT_OPTIONAL = 2;
   */
  OPTIONAL = 2,

  /**
   * @generated from enum value: MFA_REQUIREMENT_REQUIRED = 3;
   */
  REQUIRED = 3,
}

/**
 * Describes the enum cmdop.core.v1.MfaRequirement.
 */
export const MfaRequirementSchema: GenEnum<MfaRequirement> = /*@__PURE__*/
  enumDesc(file_cmdop_core_v1_common, 0);

/**
 * ScheduleTargetKind mirrors ScheduleView.target_kind (report 01 §8).
 *
 * @generated from enum cmdop.core.v1.ScheduleTargetKind
 */
export enum ScheduleTargetKind {
  /**
   * @generated from enum value: SCHEDULE_TARGET_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCHEDULE_TARGET_KIND_ALL_FLEET_MACHINES = 1;
   */
  ALL_FLEET_MACHINES = 1,

  /**
   * @generated from enum value: SCHEDULE_TARGET_KIND_SPECIFIC_MACHINES = 2;
   */
  SPECIFIC_MACHINES = 2,
}

/**
 * Describes the enum cmdop.core.v1.ScheduleTargetKind.
 */
export const ScheduleTargetKindSchema: GenEnum<ScheduleTargetKind> = /*@__PURE__*/
  enumDesc(file_cmdop_core_v1_common, 1);

/**
 * ScheduleRunStatus mirrors ScheduleRunView.status / ScheduleView.last_status
 * (report 01 §8).
 *
 * @generated from enum cmdop.core.v1.ScheduleRunStatus
 */
export enum ScheduleRunStatus {
  /**
   * @generated from enum value: SCHEDULE_RUN_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCHEDULE_RUN_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: SCHEDULE_RUN_STATUS_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: SCHEDULE_RUN_STATUS_SUCCESS = 3;
   */
  SUCCESS = 3,

  /**
   * @generated from enum value: SCHEDULE_RUN_STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum cmdop.core.v1.ScheduleRunStatus.
 */
export const ScheduleRunStatusSchema: GenEnum<ScheduleRunStatus> = /*@__PURE__*/
  enumDesc(file_cmdop_core_v1_common, 2);

