// keys.* (api-keys) request/response messages. Mirrors report 01 §9
// (api_keys.py) field-for-field. Offset pagination.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file cmdop/core/v1/keys.proto (package cmdop.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { OffsetPage } from "./common_pb";
import { file_cmdop_core_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cmdop/core/v1/keys.proto.
 */
export const file_cmdop_core_v1_keys: GenFile = /*@__PURE__*/
  fileDesc("ChhjbWRvcC9jb3JlL3YxL2tleXMucHJvdG8SDWNtZG9wLmNvcmUudjEijQIKDUFwaUtleVN1bW1hcnkSCgoCaWQYASABKAkSEAoIZmxlZXRfaWQYAiABKAkSDAoEbmFtZRgDIAEoCRISCgprZXlfcHJlZml4GAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAkSFwoKZXhwaXJlc19hdBgGIAEoCUgAiAEBEhkKDGxhc3RfdXNlZF9hdBgHIAEoCUgBiAEBEhcKCnJldm9rZWRfYXQYCCABKAlIAogBARIaCg1jcmVhdGVkX2J5X2lkGAkgASgJSAOIAQFCDQoLX2V4cGlyZXNfYXRCDwoNX2xhc3RfdXNlZF9hdEINCgtfcmV2b2tlZF9hdEIQCg5fY3JlYXRlZF9ieV9pZCJMCg9MaXN0S2V5c1JlcXVlc3QSEAoIZmxlZXRfaWQYASABKAkSJwoEcGFnZRgCIAEoCzIZLmNtZG9wLmNvcmUudjEuT2Zmc2V0UGFnZSJqCgpBcGlLZXlMaXN0EisKBWl0ZW1zGAEgAygLMhwuY21kb3AuY29yZS52MS5BcGlLZXlTdW1tYXJ5Eg4KBm9mZnNldBgCIAEoBRIQCghwZXJfcGFnZRgDIAEoBRINCgV0b3RhbBgEIAEoBSJjCg9Jc3N1ZUtleVJlcXVlc3QSEAoIZmxlZXRfaWQYASABKAkSDAoEbmFtZRgCIAEoCRIcCg9leHBpcmVzX2luX2RheXMYAyABKAVIAIgBAUISChBfZXhwaXJlc19pbl9kYXlzInkKEElzc3VlS2V5UmVzcG9uc2USCgoCaWQYASABKAkSEAoIZmxlZXRfaWQYAiABKAkSDAoEbmFtZRgDIAEoCRIRCglyYXdfdG9rZW4YBCABKAkSFwoKZXhwaXJlc19hdBgFIAEoCUgAiAEBQg0KC19leHBpcmVzX2F0IjQKEFJldm9rZUtleVJlcXVlc3QSEAoIZmxlZXRfaWQYASABKAkSDgoGa2V5X2lkGAIgASgJQrIBChFjb20uY21kb3AuY29yZS52MUIJS2V5c1Byb3RvUAFaPGdpdGh1Yi5jb20vY21kb3AvY21kb3AvZ28vcGtnL2NvcmVwcm90by9jbWRvcC9jb3JlL3YxO2NvcmV2MaICA0NDWKoCDUNtZG9wLkNvcmUuVjHKAg1DbWRvcFxDb3JlXFYx4gIZQ21kb3BcQ29yZVxWMVxHUEJNZXRhZGF0YeoCD0NtZG9wOjpDb3JlOjpWMWIGcHJvdG8z", [file_cmdop_core_v1_common]);

/**
 * ApiKeySummary — report 01 §9 (api_keys.py:60). Never carries the raw token.
 *
 * @generated from message cmdop.core.v1.ApiKeySummary
 */
export type ApiKeySummary = Message<"cmdop.core.v1.ApiKeySummary"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string fleet_id = 2;
   */
  fleetId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string key_prefix = 4;
   */
  keyPrefix: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: optional string expires_at = 6;
   */
  expiresAt?: string | undefined;

  /**
   * @generated from field: optional string last_used_at = 7;
   */
  lastUsedAt?: string | undefined;

  /**
   * @generated from field: optional string revoked_at = 8;
   */
  revokedAt?: string | undefined;

  /**
   * @generated from field: optional string created_by_id = 9;
   */
  createdById?: string | undefined;
};

/**
 * Describes the message cmdop.core.v1.ApiKeySummary.
 * Use `create(ApiKeySummarySchema)` to create a new message.
 */
export const ApiKeySummarySchema: GenMessage<ApiKeySummary> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 0);

/**
 * ListKeysRequest — GET /api/fleets/{fleet_id}/api-keys (offset).
 *
 * @generated from message cmdop.core.v1.ListKeysRequest
 */
export type ListKeysRequest = Message<"cmdop.core.v1.ListKeysRequest"> & {
  /**
   * @generated from field: string fleet_id = 1;
   */
  fleetId: string;

  /**
   * @generated from field: cmdop.core.v1.OffsetPage page = 2;
   */
  page?: OffsetPage | undefined;
};

/**
 * Describes the message cmdop.core.v1.ListKeysRequest.
 * Use `create(ListKeysRequestSchema)` to create a new message.
 */
export const ListKeysRequestSchema: GenMessage<ListKeysRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 1);

/**
 * ApiKeyList — list response (OffsetPage[ApiKeySummary]).
 *
 * @generated from message cmdop.core.v1.ApiKeyList
 */
export type ApiKeyList = Message<"cmdop.core.v1.ApiKeyList"> & {
  /**
   * @generated from field: repeated cmdop.core.v1.ApiKeySummary items = 1;
   */
  items: ApiKeySummary[];

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * @generated from field: int32 per_page = 3;
   */
  perPage: number;

  /**
   * @generated from field: int32 total = 4;
   */
  total: number;
};

/**
 * Describes the message cmdop.core.v1.ApiKeyList.
 * Use `create(ApiKeyListSchema)` to create a new message.
 */
export const ApiKeyListSchema: GenMessage<ApiKeyList> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 2);

/**
 * IssueKeyRequest — POST /api/fleets/{fleet_id}/api-keys
 * (report 01 §9, IssueApiKeyRequest:47).
 *
 * @generated from message cmdop.core.v1.IssueKeyRequest
 */
export type IssueKeyRequest = Message<"cmdop.core.v1.IssueKeyRequest"> & {
  /**
   * @generated from field: string fleet_id = 1;
   */
  fleetId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional int32 expires_in_days = 3;
   */
  expiresInDays?: number | undefined;
};

/**
 * Describes the message cmdop.core.v1.IssueKeyRequest.
 * Use `create(IssueKeyRequestSchema)` to create a new message.
 */
export const IssueKeyRequestSchema: GenMessage<IssueKeyRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 3);

/**
 * IssueKeyResponse — report 01 §9 (IssueApiKeyResponse:52).
 * raw_token is returned only here, once.
 *
 * @generated from message cmdop.core.v1.IssueKeyResponse
 */
export type IssueKeyResponse = Message<"cmdop.core.v1.IssueKeyResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string fleet_id = 2;
   */
  fleetId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string raw_token = 4;
   */
  rawToken: string;

  /**
   * @generated from field: optional string expires_at = 5;
   */
  expiresAt?: string | undefined;
};

/**
 * Describes the message cmdop.core.v1.IssueKeyResponse.
 * Use `create(IssueKeyResponseSchema)` to create a new message.
 */
export const IssueKeyResponseSchema: GenMessage<IssueKeyResponse> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 4);

/**
 * RevokeKeyRequest — DELETE /api/fleets/{fleet_id}/api-keys/{key_id} → 204.
 *
 * @generated from message cmdop.core.v1.RevokeKeyRequest
 */
export type RevokeKeyRequest = Message<"cmdop.core.v1.RevokeKeyRequest"> & {
  /**
   * @generated from field: string fleet_id = 1;
   */
  fleetId: string;

  /**
   * @generated from field: string key_id = 2;
   */
  keyId: string;
};

/**
 * Describes the message cmdop.core.v1.RevokeKeyRequest.
 * Use `create(RevokeKeyRequestSchema)` to create a new message.
 */
export const RevokeKeyRequestSchema: GenMessage<RevokeKeyRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_keys, 5);

