// tunnels.* request/response messages. Mirrors report 01 §7 (tunnels.py)
// field-for-field. Offset pagination.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file cmdop/core/v1/tunnels.proto (package cmdop.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { OffsetPage } from "./common_pb";
import { file_cmdop_core_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cmdop/core/v1/tunnels.proto.
 */
export const file_cmdop_core_v1_tunnels: GenFile = /*@__PURE__*/
  fileDesc("ChtjbWRvcC9jb3JlL3YxL3R1bm5lbHMucHJvdG8SDWNtZG9wLmNvcmUudjEiugEKClR1bm5lbFZpZXcSEQoJdHVubmVsX2lkGAEgASgJEhAKCGZsZWV0X2lkGAIgASgJEhIKCnNlc3Npb25faWQYAyABKAkSEQoJc3ViZG9tYWluGAQgASgJEhIKCmxvY2FsX2hvc3QYBSABKAkSEgoKbG9jYWxfcG9ydBgGIAEoBRIQCghwcm90b2NvbBgHIAEoCRISCgpjcmVhdGVkX2F0GAggASgJEhIKCnB1YmxpY191cmwYCSABKAkihQEKFkNvbm5lY3RlZFNlc3Npb25PcHRpb24SEgoKc2Vzc2lvbl9pZBgBIAEoCRIXCgptYWNoaW5lX2lkGAIgASgJSACIAQESEAoIaG9zdG5hbWUYAyABKAkSDQoFbGFiZWwYBCABKAkSDgoGc3RhdHVzGAUgASgJQg0KC19tYWNoaW5lX2lkIvcBChFPcGVuVHVubmVsUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhAKCHByb3RvY29sGAIgASgJEhIKCmxvY2FsX2hvc3QYAyABKAkSEgoKbG9jYWxfcG9ydBgEIAEoBRIWCglzdWJkb21haW4YBSABKAlIAIgBARI+CgdvcHRpb25zGAYgAygLMi0uY21kb3AuY29yZS52MS5PcGVuVHVubmVsUmVxdWVzdC5PcHRpb25zRW50cnkaLgoMT3B0aW9uc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCDAoKX3N1YmRvbWFpbiInChJDbG9zZVR1bm5lbFJlcXVlc3QSEQoJdHVubmVsX2lkGAEgASgJIj0KEkxpc3RUdW5uZWxzUmVxdWVzdBInCgRwYWdlGAEgASgLMhkuY21kb3AuY29yZS52MS5PZmZzZXRQYWdlIiUKEEdldFR1bm5lbFJlcXVlc3QSEQoJdHVubmVsX2lkGAEgASgJIhUKE0xpc3RTZXNzaW9uc1JlcXVlc3QiZwoKVHVubmVsTGlzdBIoCgVpdGVtcxgBIAMoCzIZLmNtZG9wLmNvcmUudjEuVHVubmVsVmlldxIOCgZvZmZzZXQYAiABKAUSEAoIcGVyX3BhZ2UYAyABKAUSDQoFdG90YWwYBCABKAUiQwoLU2Vzc2lvbkxpc3QSNAoFaXRlbXMYASADKAsyJS5jbWRvcC5jb3JlLnYxLkNvbm5lY3RlZFNlc3Npb25PcHRpb25CtQEKEWNvbS5jbWRvcC5jb3JlLnYxQgxUdW5uZWxzUHJvdG9QAVo8Z2l0aHViLmNvbS9jbWRvcC9jbWRvcC9nby9wa2cvY29yZXByb3RvL2NtZG9wL2NvcmUvdjE7Y29yZXYxogIDQ0NYqgINQ21kb3AuQ29yZS5WMcoCDUNtZG9wXENvcmVcVjHiAhlDbWRvcFxDb3JlXFYxXEdQQk1ldGFkYXRh6gIPQ21kb3A6OkNvcmU6OlYxYgZwcm90bzM", [file_cmdop_core_v1_common]);

/**
 * TunnelView — report 01 §7 (tunnels.py:90). public_url is composed server-side.
 *
 * @generated from message cmdop.core.v1.TunnelView
 */
export type TunnelView = Message<"cmdop.core.v1.TunnelView"> & {
  /**
   * @generated from field: string tunnel_id = 1;
   */
  tunnelId: string;

  /**
   * @generated from field: string fleet_id = 2;
   */
  fleetId: string;

  /**
   * @generated from field: string session_id = 3;
   */
  sessionId: string;

  /**
   * @generated from field: string subdomain = 4;
   */
  subdomain: string;

  /**
   * @generated from field: string local_host = 5;
   */
  localHost: string;

  /**
   * @generated from field: int32 local_port = 6;
   */
  localPort: number;

  /**
   * @generated from field: string protocol = 7;
   */
  protocol: string;

  /**
   * @generated from field: string created_at = 8;
   */
  createdAt: string;

  /**
   * @generated from field: string public_url = 9;
   */
  publicUrl: string;
};

/**
 * Describes the message cmdop.core.v1.TunnelView.
 * Use `create(TunnelViewSchema)` to create a new message.
 */
export const TunnelViewSchema: GenMessage<TunnelView> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 0);

/**
 * ConnectedSessionOption — report 01 §7 (tunnels.py:72), the session picker.
 *
 * @generated from message cmdop.core.v1.ConnectedSessionOption
 */
export type ConnectedSessionOption = Message<"cmdop.core.v1.ConnectedSessionOption"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: optional string machine_id = 2;
   */
  machineId?: string | undefined;

  /**
   * @generated from field: string hostname = 3;
   */
  hostname: string;

  /**
   * @generated from field: string label = 4;
   */
  label: string;

  /**
   * @generated from field: string status = 5;
   */
  status: string;
};

/**
 * Describes the message cmdop.core.v1.ConnectedSessionOption.
 * Use `create(ConnectedSessionOptionSchema)` to create a new message.
 */
export const ConnectedSessionOptionSchema: GenMessage<ConnectedSessionOption> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 1);

/**
 * OpenTunnelRequest — POST /api/tunnels (report 01 §7, tunnels.py:63).
 *
 * @generated from message cmdop.core.v1.OpenTunnelRequest
 */
export type OpenTunnelRequest = Message<"cmdop.core.v1.OpenTunnelRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string protocol = 2;
   */
  protocol: string;

  /**
   * @generated from field: string local_host = 3;
   */
  localHost: string;

  /**
   * @generated from field: int32 local_port = 4;
   */
  localPort: number;

  /**
   * @generated from field: optional string subdomain = 5;
   */
  subdomain?: string | undefined;

  /**
   * @generated from field: map<string, string> options = 6;
   */
  options: { [key: string]: string };
};

/**
 * Describes the message cmdop.core.v1.OpenTunnelRequest.
 * Use `create(OpenTunnelRequestSchema)` to create a new message.
 */
export const OpenTunnelRequestSchema: GenMessage<OpenTunnelRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 2);

/**
 * CloseTunnelRequest — DELETE /api/tunnels/{tunnel_id} → 204.
 *
 * @generated from message cmdop.core.v1.CloseTunnelRequest
 */
export type CloseTunnelRequest = Message<"cmdop.core.v1.CloseTunnelRequest"> & {
  /**
   * @generated from field: string tunnel_id = 1;
   */
  tunnelId: string;
};

/**
 * Describes the message cmdop.core.v1.CloseTunnelRequest.
 * Use `create(CloseTunnelRequestSchema)` to create a new message.
 */
export const CloseTunnelRequestSchema: GenMessage<CloseTunnelRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 3);

/**
 * ListTunnelsRequest — GET /api/tunnels (offset).
 *
 * @generated from message cmdop.core.v1.ListTunnelsRequest
 */
export type ListTunnelsRequest = Message<"cmdop.core.v1.ListTunnelsRequest"> & {
  /**
   * @generated from field: cmdop.core.v1.OffsetPage page = 1;
   */
  page?: OffsetPage | undefined;
};

/**
 * Describes the message cmdop.core.v1.ListTunnelsRequest.
 * Use `create(ListTunnelsRequestSchema)` to create a new message.
 */
export const ListTunnelsRequestSchema: GenMessage<ListTunnelsRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 4);

/**
 * GetTunnelRequest — GET /api/tunnels/{tunnel_id}.
 *
 * @generated from message cmdop.core.v1.GetTunnelRequest
 */
export type GetTunnelRequest = Message<"cmdop.core.v1.GetTunnelRequest"> & {
  /**
   * @generated from field: string tunnel_id = 1;
   */
  tunnelId: string;
};

/**
 * Describes the message cmdop.core.v1.GetTunnelRequest.
 * Use `create(GetTunnelRequestSchema)` to create a new message.
 */
export const GetTunnelRequestSchema: GenMessage<GetTunnelRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 5);

/**
 * ListSessionsRequest — GET /api/tunnels/connected-sessions.
 *
 * @generated from message cmdop.core.v1.ListSessionsRequest
 */
export type ListSessionsRequest = Message<"cmdop.core.v1.ListSessionsRequest"> & {
};

/**
 * Describes the message cmdop.core.v1.ListSessionsRequest.
 * Use `create(ListSessionsRequestSchema)` to create a new message.
 */
export const ListSessionsRequestSchema: GenMessage<ListSessionsRequest> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 6);

/**
 * TunnelList — GET /api/tunnels response (OffsetPage[TunnelView]).
 *
 * @generated from message cmdop.core.v1.TunnelList
 */
export type TunnelList = Message<"cmdop.core.v1.TunnelList"> & {
  /**
   * @generated from field: repeated cmdop.core.v1.TunnelView items = 1;
   */
  items: TunnelView[];

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * @generated from field: int32 per_page = 3;
   */
  perPage: number;

  /**
   * @generated from field: int32 total = 4;
   */
  total: number;
};

/**
 * Describes the message cmdop.core.v1.TunnelList.
 * Use `create(TunnelListSchema)` to create a new message.
 */
export const TunnelListSchema: GenMessage<TunnelList> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 7);

/**
 * SessionList — GET /api/tunnels/connected-sessions response
 * (list[ConnectedSessionOption]).
 *
 * @generated from message cmdop.core.v1.SessionList
 */
export type SessionList = Message<"cmdop.core.v1.SessionList"> & {
  /**
   * @generated from field: repeated cmdop.core.v1.ConnectedSessionOption items = 1;
   */
  items: ConnectedSessionOption[];
};

/**
 * Describes the message cmdop.core.v1.SessionList.
 * Use `create(SessionListSchema)` to create a new message.
 */
export const SessionListSchema: GenMessage<SessionList> = /*@__PURE__*/
  messageDesc(file_cmdop_core_v1_tunnels, 8);

