# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cmdop/core/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cmdop/core/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63mdop/core/v1/common.proto\x12\rcmdop.core.v1\"\x07\n\x05\x45mpty\"?\n\nOffsetPage\x12\x16\n\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x19\n\x08per_page\x18\x02 \x01(\x05R\x07perPage*\x87\x01\n\x0eMfaRequirement\x12\x1f\n\x1bMFA_REQUIREMENT_UNSPECIFIED\x10\x00\x12\x18\n\x14MFA_REQUIREMENT_NONE\x10\x01\x12\x1c\n\x18MFA_REQUIREMENT_OPTIONAL\x10\x02\x12\x1c\n\x18MFA_REQUIREMENT_REQUIRED\x10\x03*\x93\x01\n\x12ScheduleTargetKind\x12$\n SCHEDULE_TARGET_KIND_UNSPECIFIED\x10\x00\x12+\n\'SCHEDULE_TARGET_KIND_ALL_FLEET_MACHINES\x10\x01\x12*\n&SCHEDULE_TARGET_KIND_SPECIFIC_MACHINES\x10\x02*\xbb\x01\n\x11ScheduleRunStatus\x12#\n\x1fSCHEDULE_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bSCHEDULE_RUN_STATUS_PENDING\x10\x01\x12\x1f\n\x1bSCHEDULE_RUN_STATUS_RUNNING\x10\x02\x12\x1f\n\x1bSCHEDULE_RUN_STATUS_SUCCESS\x10\x03\x12\x1e\n\x1aSCHEDULE_RUN_STATUS_FAILED\x10\x04\x42\xb4\x01\n\x11\x63om.cmdop.core.v1B\x0b\x43ommonProtoP\x01Z<github.com/cmdop/cmdop/go/pkg/coreproto/cmdop/core/v1;corev1\xa2\x02\x03\x43\x43X\xaa\x02\rCmdop.Core.V1\xca\x02\rCmdop\\Core\\V1\xe2\x02\x19\x43mdop\\Core\\V1\\GPBMetadata\xea\x02\x0f\x43mdop::Core::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cmdop.core.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.cmdop.core.v1B\013CommonProtoP\001Z<github.com/cmdop/cmdop/go/pkg/coreproto/cmdop/core/v1;corev1\242\002\003CCX\252\002\rCmdop.Core.V1\312\002\rCmdop\\Core\\V1\342\002\031Cmdop\\Core\\V1\\GPBMetadata\352\002\017Cmdop::Core::V1'
  _globals['_MFAREQUIREMENT']._serialized_start=120
  _globals['_MFAREQUIREMENT']._serialized_end=255
  _globals['_SCHEDULETARGETKIND']._serialized_start=258
  _globals['_SCHEDULETARGETKIND']._serialized_end=405
  _globals['_SCHEDULERUNSTATUS']._serialized_start=408
  _globals['_SCHEDULERUNSTATUS']._serialized_end=595
  _globals['_EMPTY']._serialized_start=45
  _globals['_EMPTY']._serialized_end=52
  _globals['_OFFSETPAGE']._serialized_start=54
  _globals['_OFFSETPAGE']._serialized_end=117
# @@protoc_insertion_point(module_scope)
