from cmdop.core.v1 import common_pb2 as _common_pb2
from cmdop.core.v1 import fleets_pb2 as _fleets_pb2
from cmdop.core.v1 import keys_pb2 as _keys_pb2
from cmdop.core.v1 import machines_pb2 as _machines_pb2
from cmdop.core.v1 import schedules_pb2 as _schedules_pb2
from cmdop.core.v1 import skills_pb2 as _skills_pb2
from cmdop.core.v1 import tunnels_pb2 as _tunnels_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Envelope(_message.Message):
    __slots__ = ("id", "kind", "list_machines_req", "machine_list", "get_machine_req", "machine_detail", "update_machine_req", "machine_summary", "disable_machine_req", "machine_info_req", "machine_spend_req", "machine_spend", "machine_info_resp", "messages_req", "messages_resp", "clear_messages_req", "clear_messages_resp", "active_session_req", "active_session_resp", "ask_req", "ask_frame", "done", "pin_required", "confirm_required", "pin_answer", "confirm_answer", "list_fleets_req", "fleet_list", "get_fleet_req", "create_fleet_req", "update_fleet_req", "disable_fleet_req", "fleet_summary", "list_members_req", "member_list", "add_member_req", "set_member_role_req", "remove_member_req", "member_info", "list_fleet_machines_req", "attach_machine_req", "detach_machine_req", "machine_fleet_link", "open_tunnel_req", "close_tunnel_req", "list_tunnels_req", "get_tunnel_req", "list_sessions_req", "tunnel_view", "tunnel_list", "session_list", "list_schedules_req", "get_schedule_req", "create_schedule_req", "update_schedule_req", "delete_schedule_req", "trigger_schedule_req", "schedule_runs_req", "schedule_view", "schedule_list", "schedule_run_list", "manual_trigger_resp", "list_keys_req", "issue_key_req", "revoke_key_req", "api_key_list", "issue_key_resp", "skills_list_req", "skills_my_req", "skill_list_page", "skills_get_req", "skill_detail", "skills_install_req", "skill_install", "skills_create_req", "skill_created", "skills_update_req", "skill_updated", "skills_delete_req", "skills_versions_req", "skill_version_list", "skills_reviews_req", "skill_review_page", "skills_star_req", "skill_star", "skills_publish_req", "skills_publish_resp", "skills_publish_status_req", "skills_publish_status_resp", "skills_categories_req", "skill_category_list", "skills_tags_req", "skill_tag_list", "error", "empty")
    class Kind(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        KIND_UNSPECIFIED: _ClassVar[Envelope.Kind]
        KIND_REQUEST: _ClassVar[Envelope.Kind]
        KIND_RESPONSE: _ClassVar[Envelope.Kind]
        KIND_EVENT: _ClassVar[Envelope.Kind]
        KIND_DONE: _ClassVar[Envelope.Kind]
        KIND_ERROR: _ClassVar[Envelope.Kind]
        KIND_CALLBACK: _ClassVar[Envelope.Kind]
        KIND_ANSWER: _ClassVar[Envelope.Kind]
    KIND_UNSPECIFIED: Envelope.Kind
    KIND_REQUEST: Envelope.Kind
    KIND_RESPONSE: Envelope.Kind
    KIND_EVENT: Envelope.Kind
    KIND_DONE: Envelope.Kind
    KIND_ERROR: Envelope.Kind
    KIND_CALLBACK: Envelope.Kind
    KIND_ANSWER: Envelope.Kind
    ID_FIELD_NUMBER: _ClassVar[int]
    KIND_FIELD_NUMBER: _ClassVar[int]
    LIST_MACHINES_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_LIST_FIELD_NUMBER: _ClassVar[int]
    GET_MACHINE_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_DETAIL_FIELD_NUMBER: _ClassVar[int]
    UPDATE_MACHINE_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    DISABLE_MACHINE_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_INFO_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_SPEND_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_SPEND_FIELD_NUMBER: _ClassVar[int]
    MACHINE_INFO_RESP_FIELD_NUMBER: _ClassVar[int]
    MESSAGES_REQ_FIELD_NUMBER: _ClassVar[int]
    MESSAGES_RESP_FIELD_NUMBER: _ClassVar[int]
    CLEAR_MESSAGES_REQ_FIELD_NUMBER: _ClassVar[int]
    CLEAR_MESSAGES_RESP_FIELD_NUMBER: _ClassVar[int]
    ACTIVE_SESSION_REQ_FIELD_NUMBER: _ClassVar[int]
    ACTIVE_SESSION_RESP_FIELD_NUMBER: _ClassVar[int]
    ASK_REQ_FIELD_NUMBER: _ClassVar[int]
    ASK_FRAME_FIELD_NUMBER: _ClassVar[int]
    DONE_FIELD_NUMBER: _ClassVar[int]
    PIN_REQUIRED_FIELD_NUMBER: _ClassVar[int]
    CONFIRM_REQUIRED_FIELD_NUMBER: _ClassVar[int]
    PIN_ANSWER_FIELD_NUMBER: _ClassVar[int]
    CONFIRM_ANSWER_FIELD_NUMBER: _ClassVar[int]
    LIST_FLEETS_REQ_FIELD_NUMBER: _ClassVar[int]
    FLEET_LIST_FIELD_NUMBER: _ClassVar[int]
    GET_FLEET_REQ_FIELD_NUMBER: _ClassVar[int]
    CREATE_FLEET_REQ_FIELD_NUMBER: _ClassVar[int]
    UPDATE_FLEET_REQ_FIELD_NUMBER: _ClassVar[int]
    DISABLE_FLEET_REQ_FIELD_NUMBER: _ClassVar[int]
    FLEET_SUMMARY_FIELD_NUMBER: _ClassVar[int]
    LIST_MEMBERS_REQ_FIELD_NUMBER: _ClassVar[int]
    MEMBER_LIST_FIELD_NUMBER: _ClassVar[int]
    ADD_MEMBER_REQ_FIELD_NUMBER: _ClassVar[int]
    SET_MEMBER_ROLE_REQ_FIELD_NUMBER: _ClassVar[int]
    REMOVE_MEMBER_REQ_FIELD_NUMBER: _ClassVar[int]
    MEMBER_INFO_FIELD_NUMBER: _ClassVar[int]
    LIST_FLEET_MACHINES_REQ_FIELD_NUMBER: _ClassVar[int]
    ATTACH_MACHINE_REQ_FIELD_NUMBER: _ClassVar[int]
    DETACH_MACHINE_REQ_FIELD_NUMBER: _ClassVar[int]
    MACHINE_FLEET_LINK_FIELD_NUMBER: _ClassVar[int]
    OPEN_TUNNEL_REQ_FIELD_NUMBER: _ClassVar[int]
    CLOSE_TUNNEL_REQ_FIELD_NUMBER: _ClassVar[int]
    LIST_TUNNELS_REQ_FIELD_NUMBER: _ClassVar[int]
    GET_TUNNEL_REQ_FIELD_NUMBER: _ClassVar[int]
    LIST_SESSIONS_REQ_FIELD_NUMBER: _ClassVar[int]
    TUNNEL_VIEW_FIELD_NUMBER: _ClassVar[int]
    TUNNEL_LIST_FIELD_NUMBER: _ClassVar[int]
    SESSION_LIST_FIELD_NUMBER: _ClassVar[int]
    LIST_SCHEDULES_REQ_FIELD_NUMBER: _ClassVar[int]
    GET_SCHEDULE_REQ_FIELD_NUMBER: _ClassVar[int]
    CREATE_SCHEDULE_REQ_FIELD_NUMBER: _ClassVar[int]
    UPDATE_SCHEDULE_REQ_FIELD_NUMBER: _ClassVar[int]
    DELETE_SCHEDULE_REQ_FIELD_NUMBER: _ClassVar[int]
    TRIGGER_SCHEDULE_REQ_FIELD_NUMBER: _ClassVar[int]
    SCHEDULE_RUNS_REQ_FIELD_NUMBER: _ClassVar[int]
    SCHEDULE_VIEW_FIELD_NUMBER: _ClassVar[int]
    SCHEDULE_LIST_FIELD_NUMBER: _ClassVar[int]
    SCHEDULE_RUN_LIST_FIELD_NUMBER: _ClassVar[int]
    MANUAL_TRIGGER_RESP_FIELD_NUMBER: _ClassVar[int]
    LIST_KEYS_REQ_FIELD_NUMBER: _ClassVar[int]
    ISSUE_KEY_REQ_FIELD_NUMBER: _ClassVar[int]
    REVOKE_KEY_REQ_FIELD_NUMBER: _ClassVar[int]
    API_KEY_LIST_FIELD_NUMBER: _ClassVar[int]
    ISSUE_KEY_RESP_FIELD_NUMBER: _ClassVar[int]
    SKILLS_LIST_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILLS_MY_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_LIST_PAGE_FIELD_NUMBER: _ClassVar[int]
    SKILLS_GET_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_DETAIL_FIELD_NUMBER: _ClassVar[int]
    SKILLS_INSTALL_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_INSTALL_FIELD_NUMBER: _ClassVar[int]
    SKILLS_CREATE_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_CREATED_FIELD_NUMBER: _ClassVar[int]
    SKILLS_UPDATE_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_UPDATED_FIELD_NUMBER: _ClassVar[int]
    SKILLS_DELETE_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILLS_VERSIONS_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_VERSION_LIST_FIELD_NUMBER: _ClassVar[int]
    SKILLS_REVIEWS_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_REVIEW_PAGE_FIELD_NUMBER: _ClassVar[int]
    SKILLS_STAR_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_STAR_FIELD_NUMBER: _ClassVar[int]
    SKILLS_PUBLISH_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILLS_PUBLISH_RESP_FIELD_NUMBER: _ClassVar[int]
    SKILLS_PUBLISH_STATUS_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILLS_PUBLISH_STATUS_RESP_FIELD_NUMBER: _ClassVar[int]
    SKILLS_CATEGORIES_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_CATEGORY_LIST_FIELD_NUMBER: _ClassVar[int]
    SKILLS_TAGS_REQ_FIELD_NUMBER: _ClassVar[int]
    SKILL_TAG_LIST_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    EMPTY_FIELD_NUMBER: _ClassVar[int]
    id: int
    kind: Envelope.Kind
    list_machines_req: _machines_pb2.ListMachinesRequest
    machine_list: _machines_pb2.MachineList
    get_machine_req: _machines_pb2.GetMachineRequest
    machine_detail: _machines_pb2.MachineDetail
    update_machine_req: _machines_pb2.UpdateMachineRequest
    machine_summary: _machines_pb2.MachineSummary
    disable_machine_req: _machines_pb2.DisableMachineRequest
    machine_info_req: _machines_pb2.MachineInfoRequest
    machine_spend_req: _machines_pb2.MachineSpendRequest
    machine_spend: _machines_pb2.MachineSpend
    machine_info_resp: _machines_pb2.MachineInfoResponse
    messages_req: _machines_pb2.MessagesRequest
    messages_resp: _machines_pb2.MessagesResponse
    clear_messages_req: _machines_pb2.ClearMessagesRequest
    clear_messages_resp: _machines_pb2.ClearMessagesResponse
    active_session_req: _machines_pb2.ActiveSessionRequest
    active_session_resp: _machines_pb2.ActiveSessionResponse
    ask_req: _machines_pb2.AskRequest
    ask_frame: _machines_pb2.AskFrame
    done: _machines_pb2.DoneInfo
    pin_required: _machines_pb2.PinRequired
    confirm_required: _machines_pb2.ConfirmRequired
    pin_answer: _machines_pb2.PinAnswer
    confirm_answer: _machines_pb2.ConfirmAnswer
    list_fleets_req: _fleets_pb2.ListFleetsRequest
    fleet_list: _fleets_pb2.FleetList
    get_fleet_req: _fleets_pb2.GetFleetRequest
    create_fleet_req: _fleets_pb2.CreateFleetRequest
    update_fleet_req: _fleets_pb2.UpdateFleetRequest
    disable_fleet_req: _fleets_pb2.DisableFleetRequest
    fleet_summary: _fleets_pb2.FleetSummary
    list_members_req: _fleets_pb2.ListMembersRequest
    member_list: _fleets_pb2.MemberList
    add_member_req: _fleets_pb2.AddMemberRequest
    set_member_role_req: _fleets_pb2.SetMemberRoleRequest
    remove_member_req: _fleets_pb2.RemoveMemberRequest
    member_info: _fleets_pb2.MemberInfo
    list_fleet_machines_req: _fleets_pb2.ListFleetMachinesRequest
    attach_machine_req: _fleets_pb2.AttachMachineRequest
    detach_machine_req: _fleets_pb2.DetachMachineRequest
    machine_fleet_link: _fleets_pb2.MachineFleetLink
    open_tunnel_req: _tunnels_pb2.OpenTunnelRequest
    close_tunnel_req: _tunnels_pb2.CloseTunnelRequest
    list_tunnels_req: _tunnels_pb2.ListTunnelsRequest
    get_tunnel_req: _tunnels_pb2.GetTunnelRequest
    list_sessions_req: _tunnels_pb2.ListSessionsRequest
    tunnel_view: _tunnels_pb2.TunnelView
    tunnel_list: _tunnels_pb2.TunnelList
    session_list: _tunnels_pb2.SessionList
    list_schedules_req: _schedules_pb2.ListSchedulesRequest
    get_schedule_req: _schedules_pb2.GetScheduleRequest
    create_schedule_req: _schedules_pb2.CreateScheduleRequest
    update_schedule_req: _schedules_pb2.UpdateScheduleRequest
    delete_schedule_req: _schedules_pb2.DeleteScheduleRequest
    trigger_schedule_req: _schedules_pb2.TriggerScheduleRequest
    schedule_runs_req: _schedules_pb2.ScheduleRunsRequest
    schedule_view: _schedules_pb2.ScheduleView
    schedule_list: _schedules_pb2.ScheduleList
    schedule_run_list: _schedules_pb2.ScheduleRunList
    manual_trigger_resp: _schedules_pb2.ManualTriggerResponse
    list_keys_req: _keys_pb2.ListKeysRequest
    issue_key_req: _keys_pb2.IssueKeyRequest
    revoke_key_req: _keys_pb2.RevokeKeyRequest
    api_key_list: _keys_pb2.ApiKeyList
    issue_key_resp: _keys_pb2.IssueKeyResponse
    skills_list_req: _skills_pb2.SkillsListRequest
    skills_my_req: _skills_pb2.SkillsMyRequest
    skill_list_page: _skills_pb2.SkillListPage
    skills_get_req: _skills_pb2.SkillsGetRequest
    skill_detail: _skills_pb2.SkillDetail
    skills_install_req: _skills_pb2.SkillsInstallRequest
    skill_install: _skills_pb2.SkillInstall
    skills_create_req: _skills_pb2.SkillsCreateRequest
    skill_created: _skills_pb2.SkillCreated
    skills_update_req: _skills_pb2.SkillsUpdateRequest
    skill_updated: _skills_pb2.SkillUpdated
    skills_delete_req: _skills_pb2.SkillsDeleteRequest
    skills_versions_req: _skills_pb2.SkillsVersionsRequest
    skill_version_list: _skills_pb2.SkillVersionList
    skills_reviews_req: _skills_pb2.SkillsReviewsRequest
    skill_review_page: _skills_pb2.SkillReviewPage
    skills_star_req: _skills_pb2.SkillsStarRequest
    skill_star: _skills_pb2.SkillStar
    skills_publish_req: _skills_pb2.SkillsPublishRequest
    skills_publish_resp: _skills_pb2.SkillsPublishResponse
    skills_publish_status_req: _skills_pb2.SkillsPublishStatusRequest
    skills_publish_status_resp: _skills_pb2.SkillsPublishStatusResponse
    skills_categories_req: _skills_pb2.SkillsCategoriesRequest
    skill_category_list: _skills_pb2.SkillCategoryList
    skills_tags_req: _skills_pb2.SkillsTagsRequest
    skill_tag_list: _skills_pb2.SkillTagList
    error: _machines_pb2.ErrorInfo
    empty: _common_pb2.Empty
    def __init__(self, id: _Optional[int] = ..., kind: _Optional[_Union[Envelope.Kind, str]] = ..., list_machines_req: _Optional[_Union[_machines_pb2.ListMachinesRequest, _Mapping]] = ..., machine_list: _Optional[_Union[_machines_pb2.MachineList, _Mapping]] = ..., get_machine_req: _Optional[_Union[_machines_pb2.GetMachineRequest, _Mapping]] = ..., machine_detail: _Optional[_Union[_machines_pb2.MachineDetail, _Mapping]] = ..., update_machine_req: _Optional[_Union[_machines_pb2.UpdateMachineRequest, _Mapping]] = ..., machine_summary: _Optional[_Union[_machines_pb2.MachineSummary, _Mapping]] = ..., disable_machine_req: _Optional[_Union[_machines_pb2.DisableMachineRequest, _Mapping]] = ..., machine_info_req: _Optional[_Union[_machines_pb2.MachineInfoRequest, _Mapping]] = ..., machine_spend_req: _Optional[_Union[_machines_pb2.MachineSpendRequest, _Mapping]] = ..., machine_spend: _Optional[_Union[_machines_pb2.MachineSpend, _Mapping]] = ..., machine_info_resp: _Optional[_Union[_machines_pb2.MachineInfoResponse, _Mapping]] = ..., messages_req: _Optional[_Union[_machines_pb2.MessagesRequest, _Mapping]] = ..., messages_resp: _Optional[_Union[_machines_pb2.MessagesResponse, _Mapping]] = ..., clear_messages_req: _Optional[_Union[_machines_pb2.ClearMessagesRequest, _Mapping]] = ..., clear_messages_resp: _Optional[_Union[_machines_pb2.ClearMessagesResponse, _Mapping]] = ..., active_session_req: _Optional[_Union[_machines_pb2.ActiveSessionRequest, _Mapping]] = ..., active_session_resp: _Optional[_Union[_machines_pb2.ActiveSessionResponse, _Mapping]] = ..., ask_req: _Optional[_Union[_machines_pb2.AskRequest, _Mapping]] = ..., ask_frame: _Optional[_Union[_machines_pb2.AskFrame, _Mapping]] = ..., done: _Optional[_Union[_machines_pb2.DoneInfo, _Mapping]] = ..., pin_required: _Optional[_Union[_machines_pb2.PinRequired, _Mapping]] = ..., confirm_required: _Optional[_Union[_machines_pb2.ConfirmRequired, _Mapping]] = ..., pin_answer: _Optional[_Union[_machines_pb2.PinAnswer, _Mapping]] = ..., confirm_answer: _Optional[_Union[_machines_pb2.ConfirmAnswer, _Mapping]] = ..., list_fleets_req: _Optional[_Union[_fleets_pb2.ListFleetsRequest, _Mapping]] = ..., fleet_list: _Optional[_Union[_fleets_pb2.FleetList, _Mapping]] = ..., get_fleet_req: _Optional[_Union[_fleets_pb2.GetFleetRequest, _Mapping]] = ..., create_fleet_req: _Optional[_Union[_fleets_pb2.CreateFleetRequest, _Mapping]] = ..., update_fleet_req: _Optional[_Union[_fleets_pb2.UpdateFleetRequest, _Mapping]] = ..., disable_fleet_req: _Optional[_Union[_fleets_pb2.DisableFleetRequest, _Mapping]] = ..., fleet_summary: _Optional[_Union[_fleets_pb2.FleetSummary, _Mapping]] = ..., list_members_req: _Optional[_Union[_fleets_pb2.ListMembersRequest, _Mapping]] = ..., member_list: _Optional[_Union[_fleets_pb2.MemberList, _Mapping]] = ..., add_member_req: _Optional[_Union[_fleets_pb2.AddMemberRequest, _Mapping]] = ..., set_member_role_req: _Optional[_Union[_fleets_pb2.SetMemberRoleRequest, _Mapping]] = ..., remove_member_req: _Optional[_Union[_fleets_pb2.RemoveMemberRequest, _Mapping]] = ..., member_info: _Optional[_Union[_fleets_pb2.MemberInfo, _Mapping]] = ..., list_fleet_machines_req: _Optional[_Union[_fleets_pb2.ListFleetMachinesRequest, _Mapping]] = ..., attach_machine_req: _Optional[_Union[_fleets_pb2.AttachMachineRequest, _Mapping]] = ..., detach_machine_req: _Optional[_Union[_fleets_pb2.DetachMachineRequest, _Mapping]] = ..., machine_fleet_link: _Optional[_Union[_fleets_pb2.MachineFleetLink, _Mapping]] = ..., open_tunnel_req: _Optional[_Union[_tunnels_pb2.OpenTunnelRequest, _Mapping]] = ..., close_tunnel_req: _Optional[_Union[_tunnels_pb2.CloseTunnelRequest, _Mapping]] = ..., list_tunnels_req: _Optional[_Union[_tunnels_pb2.ListTunnelsRequest, _Mapping]] = ..., get_tunnel_req: _Optional[_Union[_tunnels_pb2.GetTunnelRequest, _Mapping]] = ..., list_sessions_req: _Optional[_Union[_tunnels_pb2.ListSessionsRequest, _Mapping]] = ..., tunnel_view: _Optional[_Union[_tunnels_pb2.TunnelView, _Mapping]] = ..., tunnel_list: _Optional[_Union[_tunnels_pb2.TunnelList, _Mapping]] = ..., session_list: _Optional[_Union[_tunnels_pb2.SessionList, _Mapping]] = ..., list_schedules_req: _Optional[_Union[_schedules_pb2.ListSchedulesRequest, _Mapping]] = ..., get_schedule_req: _Optional[_Union[_schedules_pb2.GetScheduleRequest, _Mapping]] = ..., create_schedule_req: _Optional[_Union[_schedules_pb2.CreateScheduleRequest, _Mapping]] = ..., update_schedule_req: _Optional[_Union[_schedules_pb2.UpdateScheduleRequest, _Mapping]] = ..., delete_schedule_req: _Optional[_Union[_schedules_pb2.DeleteScheduleRequest, _Mapping]] = ..., trigger_schedule_req: _Optional[_Union[_schedules_pb2.TriggerScheduleRequest, _Mapping]] = ..., schedule_runs_req: _Optional[_Union[_schedules_pb2.ScheduleRunsRequest, _Mapping]] = ..., schedule_view: _Optional[_Union[_schedules_pb2.ScheduleView, _Mapping]] = ..., schedule_list: _Optional[_Union[_schedules_pb2.ScheduleList, _Mapping]] = ..., schedule_run_list: _Optional[_Union[_schedules_pb2.ScheduleRunList, _Mapping]] = ..., manual_trigger_resp: _Optional[_Union[_schedules_pb2.ManualTriggerResponse, _Mapping]] = ..., list_keys_req: _Optional[_Union[_keys_pb2.ListKeysRequest, _Mapping]] = ..., issue_key_req: _Optional[_Union[_keys_pb2.IssueKeyRequest, _Mapping]] = ..., revoke_key_req: _Optional[_Union[_keys_pb2.RevokeKeyRequest, _Mapping]] = ..., api_key_list: _Optional[_Union[_keys_pb2.ApiKeyList, _Mapping]] = ..., issue_key_resp: _Optional[_Union[_keys_pb2.IssueKeyResponse, _Mapping]] = ..., skills_list_req: _Optional[_Union[_skills_pb2.SkillsListRequest, _Mapping]] = ..., skills_my_req: _Optional[_Union[_skills_pb2.SkillsMyRequest, _Mapping]] = ..., skill_list_page: _Optional[_Union[_skills_pb2.SkillListPage, _Mapping]] = ..., skills_get_req: _Optional[_Union[_skills_pb2.SkillsGetRequest, _Mapping]] = ..., skill_detail: _Optional[_Union[_skills_pb2.SkillDetail, _Mapping]] = ..., skills_install_req: _Optional[_Union[_skills_pb2.SkillsInstallRequest, _Mapping]] = ..., skill_install: _Optional[_Union[_skills_pb2.SkillInstall, _Mapping]] = ..., skills_create_req: _Optional[_Union[_skills_pb2.SkillsCreateRequest, _Mapping]] = ..., skill_created: _Optional[_Union[_skills_pb2.SkillCreated, _Mapping]] = ..., skills_update_req: _Optional[_Union[_skills_pb2.SkillsUpdateRequest, _Mapping]] = ..., skill_updated: _Optional[_Union[_skills_pb2.SkillUpdated, _Mapping]] = ..., skills_delete_req: _Optional[_Union[_skills_pb2.SkillsDeleteRequest, _Mapping]] = ..., skills_versions_req: _Optional[_Union[_skills_pb2.SkillsVersionsRequest, _Mapping]] = ..., skill_version_list: _Optional[_Union[_skills_pb2.SkillVersionList, _Mapping]] = ..., skills_reviews_req: _Optional[_Union[_skills_pb2.SkillsReviewsRequest, _Mapping]] = ..., skill_review_page: _Optional[_Union[_skills_pb2.SkillReviewPage, _Mapping]] = ..., skills_star_req: _Optional[_Union[_skills_pb2.SkillsStarRequest, _Mapping]] = ..., skill_star: _Optional[_Union[_skills_pb2.SkillStar, _Mapping]] = ..., skills_publish_req: _Optional[_Union[_skills_pb2.SkillsPublishRequest, _Mapping]] = ..., skills_publish_resp: _Optional[_Union[_skills_pb2.SkillsPublishResponse, _Mapping]] = ..., skills_publish_status_req: _Optional[_Union[_skills_pb2.SkillsPublishStatusRequest, _Mapping]] = ..., skills_publish_status_resp: _Optional[_Union[_skills_pb2.SkillsPublishStatusResponse, _Mapping]] = ..., skills_categories_req: _Optional[_Union[_skills_pb2.SkillsCategoriesRequest, _Mapping]] = ..., skill_category_list: _Optional[_Union[_skills_pb2.SkillCategoryList, _Mapping]] = ..., skills_tags_req: _Optional[_Union[_skills_pb2.SkillsTagsRequest, _Mapping]] = ..., skill_tag_list: _Optional[_Union[_skills_pb2.SkillTagList, _Mapping]] = ..., error: _Optional[_Union[_machines_pb2.ErrorInfo, _Mapping]] = ..., empty: _Optional[_Union[_common_pb2.Empty, _Mapping]] = ...) -> None: ...
